# Change these first
owner: GamerIndiaOfficial # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:- name: Projects-of-Dream
  url: https://gamerindiaofficial.github.io/Projects-of-dream
- name: Internet Archive
  url: https://archive.org
- name: Open Library
  url: https://openlibrary.org
- name: Mozilla
  url: https://mozilla.org
- name: Wikipedia
  url: https://wikipedia.org
- name: Proton
  url: https://proton.me
- name: Google
  url: https://google.com
- name: YouTube
  url: https://youtube.com
- name: Amazon
  url: https://amazon.com
- name: Facebook
  url: https://facebook.com
- name: Twitter (X)
  url: https://twitter.com
- name: Instagram
  url: https://instagram.com
- name: Reddit
  url: https://reddit.com
- name: LinkedIn
  url: https://linkedin.com
- name: Netflix
  url: https://netflix.com
- name: GitHub
  url: https://github.com
- name: Stack Overflow
  url: https://stackoverflow.com
- name: Quora
  url: https://quora.com
- name: Pinterest
  url: https://pinterest.com
- name: Yahoo
  url: https://yahoo.com
- name: Bing
  url: https://bing.com
- name: eBay
  url: https://ebay.com
- name: Zoom
  url: https://zoom.us
- name: Dropbox
  url: https://dropbox.com
- name: Spotify
  url: https://spotify.com
- name: Microsoft
  url: https://microsoft.com
- name: Apple
  url: https://apple.com
- name: Adobe
  url: https://adobe.com
- name: Medium
  url: https://medium.com
- name: Coursera
  url: https://coursera.org
- name: Khan Academy
  url: https://khanacademy.org
- name: TED
  url: https://ted.com
- name: Twitch
  url: https://twitch.tv
- name: Discord
  url: https://discord.com
- name: Canva
  url: https://canva.com
- name: Udemy
  url: https://udemy.com
- name: Duolingo
  url: https://duolingo.com
- name: Shopify
  url: https://shopify.com
- name: Wikimedia Commons
  url: https://commons.wikimedia.org
- name: BBC
  url: https://bbc.com
- name: The New York Times
  url: https://nytimes.com
- name: NPR
  url: https://npr.org
- name: Bloomberg
  url: https://bloomberg.com
- name: The Guardian
  url: https://theguardian.com
- name: Reuters
  url: https://reuters.com
- name: National Geographic
  url: https://nationalgeographic.com
- name: Smithsonian
  url: https://si.edu
- name: IMDb
  url: https://imdb.com
- name: Rotten Tomatoes
  url: https://rottentomatoes.com
- name: Goodreads
  url: https://goodreads.com
- name: Pocket
  url: https://getpocket.com
- name: Hacker News
  url: https://news.ycombinator.com
- name: Ars Technica
  url: https://arstechnica.com
- name: WIRED
  url: https://wired.com
- name: Verge
  url: https://theverge.com
- name: Slashdot
  url: https://slashdot.org
- name: Engadget
  url: https://engadget.com
- name: Lifehacker
  url: https://lifehacker.com
- name: MakeUseOf
  url: https://makeuseof.com
- name: How-To Geek
  url: https://howtogeek.com
- name: Stack Exchange
  url: https://stackexchange.com
- name: ScienceDirect
  url: https://sciencedirect.com
- name: Springer
  url: https://springer.com
- name: JSTOR
  url: https://jstor.org
- name: Elsevier
  url: https://elsevier.com
- name: PubMed
  url: https://pubmed.ncbi.nlm.nih.gov
- name: GitLab
  url: https://gitlab.com
- name: Bitbucket
  url: https://bitbucket.org
- name: Trello
  url: https://trello.com
- name: Notion
  url: https://notion.so
- name: Evernote
  url: https://evernote.com
- name: Zoho
  url: https://zoho.com
- name: Asana
  url: https://asana.com
- name: Monday.com
  url: https://monday.com
- name: Slack
  url: https://slack.com
- name: Basecamp
  url: https://basecamp.com
- name: ClickUp
  url: https://clickup.com
- name: Wix
  url: https://wix.com
- name: WordPress
  url: https://wordpress.org
- name: Squarespace
  url: https://squarespace.com
- name: Tumblr
  url: https://tumblr.com
- name: Weebly
  url: https://weebly.com
- name: Behance
  url: https://behance.net
- name: Dribbble
  url: https://dribbble.com
- name: DeviantArt
  url: https://deviantart.com




status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
